baseURL: http://example.org/
languageCode: en-us
title: My Blog
theme: mero
disableKinds: taxonomyTerm
module:
  hugoVersion:
    extended: no
    min: 0.80.0
params:
  author: Olga V. Chyzh
  dateFormat: '2006-01-02'
  description: My awesome blog
  footer:
    message: '&copy; 2018 Name'
  introduction:
    text: 'I am an Assistant Professor in the Department of Political Science at the University of Toronto.  I earned my PhD in Political Science from the University of Iowa in 2013.  My research areas are political methodology and international relations.  I have published on such topics as human rights, international trade, autocratic regimes, and network analysis. My articles have appeared or are forthcoming in the American Journal of Political Science, Journal of Politics, Political Analysis, and Canadian Journal of Political Science, among others. Please visit my research page to download recent publications and working papers. My teaching page provides additional information about the courses I have instructed and some tools I have developed for my classrooms.'
  mainImage: images/chyzh-olga.jpg
  social:
    list:
      - class: fab
        icon: fa-telegram
        url: 'mailto:olga.chyzh@utoronto.ca'
      - class: fab
        icon: fa-github
        url: 'https://github.com/ochyzh'
      - class: fab
        icon: fa-twitter
        url: 'https://twitter.com/olga_chyzh'



